# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_translator": "00_data.ipynb",
         "default_translator_path": "00_data.ipynb",
         "strip_html": "00_data.ipynb",
         "OriTraTranslation": "00_data.ipynb",
         "create_ori_trans_dataframe": "00_data.ipynb",
         "PrettyDataset": "00_data.ipynb",
         "print_dataframe_table": "00_data.ipynb",
         "plot_text_length": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://pandya6988.github.io/diin_text/"

git_url = "https://github.com/pandya6988/diin_text/tree/master/"

def custom_doc_links(name): return None
