# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_translator": "00_data.ipynb",
         "default_translator_path": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://pandya6988.github.io/diin_text/"

git_url = "https://github.com/pandya6988/diin_text/tree/master/"

def custom_doc_links(name): return None
