# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_data.ipynb (unless otherwise specified).

__all__ = ['generate_translator', 'default_translator_path', 'strip_html', 'OriTraTranslation']

# Cell
default_translator_path = 'translate-en_de-1_0.argosmodel'
def generate_translator(path='translate-en_de-1_0.argosmodel'):
    '''
        path[str]: path to file from https://www.argosopentech.com/argospm/index/
    '''
    package.install_from_path('translate-en_de-1_0.argosmodel')
    installed_languages = translate.get_installed_languages()
    [str(lang) for lang in installed_languages]
    translation_en_de = installed_languages[0].get_translation(installed_languages[1])
    return translation_en_de

# Cell
def strip_html(text):
    '''
    Remove html text
    '''
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

# Cell
class OriTraTranslation():
    def __init__(self, ori_text, path):
        '''
        Input:
            ori_text[str]: Original text
            path[str]: path to file from https://www.argosopentech.com/argospm/index

        Output:
            dict[dict]: { ori_text:Original text, translated_text: translated text }
        '''
        self.ori_text = ori_text
        self.translator = generate_translator(path)

    def __len__(self): return len(self.ori_text)

    def __getitem__(self, idx):
        return {
            'ori_text': self.ori_text[idx],
            'translated_text' : self.translator.translate(self.ori_text[idx])
        }